name: Coderco Combined

on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: install dependencies
        run: |
          cd chapter4
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: run test
        run: |
          cd chapter4
          python -m unittest discover

      - name: notify us of success
        run: echo "Test passed on python ${{ matrix.python-version }}"
        if: success()